# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
"""RecordNsec - NIOS DNS NSEC record.

All 15 properties from ``components.schemas.RecordNsec`` in the v2.14 DNS
swagger are represented here.  DNSSEC NSEC records are generated by the zone
signer; 13 of 15 fields are read-only.  The ``cloud_info`` field is writable.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from ibx_nios_sdk.dns.models._shared import CloudInfo

# ---------------------------------------------------------------------------
# Read-only fields (swagger readOnly: true)
# ---------------------------------------------------------------------------
READONLY_FIELDS: frozenset[str] = frozenset(
    {
        "cloud_info",
        "creation_time",
        "creator",
        "dns_name",
        "dns_next_owner_name",
        "last_queried",
        "name",
        "next_owner_name",
        "rrset_types",
        "ttl",
        "use_ttl",
        "uuid",
        "view",
        "zone",
    }
)


# ---------------------------------------------------------------------------
# Main RecordNsec model
# ---------------------------------------------------------------------------


class RecordNsec(BaseModel):
    """NIOS DNS NSEC record.

    All 15 swagger properties are present.  Almost every field is read-only
    (generated by the DNSSEC signer).  ``cloud_info`` is the only non-ref
    writable field.  Read-only fields are collected in :data:`READONLY_FIELDS`;
    the resource strips them before PUT/POST.
    """

    model_config = ConfigDict(populate_by_name=True, extra="allow")

    ref: str | None = Field(default=None, alias="_ref", description="The reference to the object.")

    # --- writable: cloud delegation metadata ---
    cloud_info: CloudInfo | None = Field(
        default=None, description="Cloud API related information for the object."
    )  # --- read-only ---
    creation_time: int | None = Field(
        default=None, description="Time that the record was created."
    )  # --- read-only ---
    creator: Literal["SYSTEM", "STATIC", "DYNAMIC"] | str | None = Field(
        default=None, description="Creator of the record."
    )  # --- read-only ---
    dns_name: str | None = Field(
        default=None, description="Name for an NSEC record in punycode format."
    )  # --- read-only: DNS-format next owner name ---
    dns_next_owner_name: str | None = Field(
        default=None, description="Name of the next owner in punycode format."
    )  # --- read-only ---
    last_queried: int | None = Field(
        default=None, description="The time of the last DNS query in Epoch seconds format."
    )  # --- read-only: owner name ---
    name: str | None = Field(
        default=None, description="The name of the NSEC record in FQDN format."
    )  # --- read-only: next owner name in the canonical chain ---
    next_owner_name: str | None = Field(
        default=None,
        description="Name of the next owner that has authoritative data or that contains a delegation point NS record.",
    )  # --- read-only: list of RR type mnemonics covered ---
    rrset_types: list[str] | None = Field(
        default=None,
        description="The RRSet types that exist at the original owner name of the NSEC RR.",
    )  # --- read-only ---
    ttl: int | None = Field(
        default=None,
        description="The Time To Live (TTL) value for the record. A 32-bit unsigned integer that represents the duration, in seconds, for which the record is valid (cached). Zero indicates that the record should not be cached.",
    )  # --- read-only ---
    use_ttl: bool | None = Field(
        default=None, description="Use flag for: ttl"
    )  # --- read-only ---
    uuid: str | None = Field(
        default=None, description="Universally Unique ID assigned for this object"
    )  # --- read-only ---
    view: str | None = Field(
        default=None,
        description='The name of the DNS View in which the record resides. Example: "external".',
    )  # --- read-only ---
    zone: str | None = Field(
        default=None,
        description='The name of the zone in which the record resides. Example: "zone.com". If a view is not specified when searching by zone, the default view is used.',
    )
