# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
"""RecordDs - NIOS DNS DS record.

All 17 properties from ``components.schemas.RecordDs`` in the v2.14 DNS
swagger are represented here.  DNSSEC DS records are generated by the zone
signer; 15 of 17 fields are read-only.  The ``cloud_info`` field is writable
(the only non-_ref writable field).
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from ibx_nios_sdk.dns.models._shared import CloudInfo

# ---------------------------------------------------------------------------
# Read-only fields (swagger readOnly: true)
# ---------------------------------------------------------------------------
READONLY_FIELDS: frozenset[str] = frozenset(
    {
        "algorithm",
        "cloud_info",
        "comment",
        "creation_time",
        "creator",
        "digest",
        "digest_type",
        "dns_name",
        "key_tag",
        "last_queried",
        "name",
        "ttl",
        "use_ttl",
        "uuid",
        "view",
        "zone",
    }
)


# ---------------------------------------------------------------------------
# Main RecordDs model
# ---------------------------------------------------------------------------


class RecordDs(BaseModel):
    """NIOS DNS DS record.

    All 17 swagger properties are present.  Almost every field is read-only
    (generated by the DNSSEC signer).  ``cloud_info`` is the only non-ref
    writable field.  Read-only fields are collected in :data:`READONLY_FIELDS`;
    the resource strips them before PUT/POST.
    """

    model_config = ConfigDict(populate_by_name=True, extra="allow")

    ref: str | None = Field(default=None, alias="_ref", description="The reference to the object.")

    # --- read-only: signing algorithm ---
    algorithm: (
        Literal[
            "DSA",
            "ECDSAP256SHA256",
            "ECDSAP384SHA384",
            "NSEC3DSA",
            "NSEC3RSASHA1",
            "RSAMD5",
            "RSASHA1",
            "RSASHA256",
            "RSASHA512",
        ]
        | str
        | None
    ) = Field(
        default=None,
        description="The algorithm of the DNSKEY RR to which this DS RR refers. It uses the same algorithm values and types as the corresponding DNSKEY RR.",
    )  # --- writable: cloud delegation metadata ---
    cloud_info: CloudInfo | None = Field(
        default=None, description="Cloud API related information for the object."
    )  # --- read-only ---
    comment: str | None = Field(
        default=None, description="The comment for the record."
    )  # --- read-only ---
    creation_time: int | None = Field(
        default=None, description="The creation time of the record."
    )  # --- read-only ---
    creator: Literal["SYSTEM"] | str | None = Field(
        default=None, description="Creator of the record."
    )  # --- read-only: hex-encoded DS digest ---
    digest: str | None = Field(
        default=None,
        description="The digest of the DNSKEY resource record that is stored in a DS Record object.",
    )  # --- read-only: digest algorithm type ---
    digest_type: Literal["SHA1", "SHA256"] | str | None = Field(
        default=None, description="The algorithm used to construct the digest."
    )  # --- read-only ---
    dns_name: str | None = Field(
        default=None, description="The name for the DS record in punycode format."
    )  # --- read-only ---
    key_tag: int | None = Field(
        default=None,
        description="The key tag value that is used to determine which key to use to verify signatures.",
    )  # --- read-only ---
    last_queried: int | None = Field(
        default=None, description="The time of the last DNS query in Epoch seconds format."
    )  # --- read-only: owner name ---
    name: str | None = Field(
        default=None, description="The name of the DNS DS record in FQDN format."
    )  # --- read-only ---
    ttl: int | None = Field(
        default=None,
        description="The Time To Live (TTL) value for the record. A 32-bit unsigned integer that represents the duration, in seconds, for which the record is valid (cached). Zero indicates that the record should not be cached.",
    )  # --- read-only ---
    use_ttl: bool | None = Field(
        default=None, description="Use flag for: ttl"
    )  # --- read-only ---
    uuid: str | None = Field(
        default=None, description="Universally Unique ID assigned for this object"
    )  # --- read-only ---
    view: str | None = Field(
        default=None,
        description='The name of the DNS View in which the record resides. Example: "external".',
    )  # --- read-only ---
    zone: str | None = Field(
        default=None,
        description='The name of the zone in which the record resides. Example: "zone.com". If a view is not specified when searching by zone, the default view is used.',
    )
