# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
"""RecordRrsig - NIOS DNS RRSIG record.

All 22 properties from ``components.schemas.RecordRrsig`` in the v2.14 DNS
swagger are represented here.  DNSSEC RRSIG records are generated by the zone
signer; 20 of 22 fields are read-only.  The ``cloud_info`` field is writable.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from ibx_nios_sdk.dns.models._shared import CloudInfo

# ---------------------------------------------------------------------------
# Read-only fields (swagger readOnly: true)
# ---------------------------------------------------------------------------
READONLY_FIELDS: frozenset[str] = frozenset(
    {
        "algorithm",
        "cloud_info",
        "creation_time",
        "creator",
        "dns_name",
        "dns_signer_name",
        "expiration_time",
        "inception_time",
        "key_tag",
        "labels",
        "last_queried",
        "name",
        "original_ttl",
        "signature",
        "signer_name",
        "ttl",
        "type_covered",
        "use_ttl",
        "uuid",
        "view",
        "zone",
    }
)


# ---------------------------------------------------------------------------
# Main RecordRrsig model
# ---------------------------------------------------------------------------


class RecordRrsig(BaseModel):
    """NIOS DNS RRSIG record.

    All 22 swagger properties are present.  Almost every field is read-only
    (generated by the DNSSEC signer).  ``cloud_info`` is the only non-ref
    writable field.  Read-only fields are collected in :data:`READONLY_FIELDS`;
    the resource strips them before PUT/POST.
    """

    model_config = ConfigDict(populate_by_name=True, extra="allow")

    ref: str | None = Field(default=None, alias="_ref", description="The reference to the object.")

    # --- read-only: signing algorithm ---
    algorithm: (
        Literal[
            "DSA",
            "ECDSAP256SHA256",
            "ECDSAP384SHA384",
            "NSEC3DSA",
            "NSEC3RSASHA1",
            "RSAMD5",
            "RSASHA1",
            "RSASHA256",
            "RSASHA512",
        ]
        | str
        | None
    ) = Field(
        default=None,
        description="The cryptographic algorithm that was used to create the signature. It uses the same algorithm types as the DNSKEY record indicated in the key tag field.",
    )  # --- writable: cloud delegation metadata ---
    cloud_info: CloudInfo | None = Field(
        default=None, description="Cloud API related information for the object."
    )  # --- read-only ---
    creation_time: int | None = Field(
        default=None, description="The creation time of the record."
    )  # --- read-only ---
    creator: Literal["SYSTEM", "STATIC", "DYNAMIC"] | str | None = Field(
        default=None, description="The record creator."
    )  # --- read-only ---
    dns_name: str | None = Field(
        default=None, description="Name for an RRSIG record in punycode format."
    )  # --- read-only: DNS-format signer name ---
    dns_signer_name: str | None = Field(
        default=None,
        description="The domain name, in punycode format, of the zone that contains the signed RRset.",
    )  # --- read-only: signature expiration timestamp ---
    expiration_time: int | None = Field(
        default=None, description="The expiry time of an RRSIG record in Epoch seconds format."
    )  # --- read-only: signature inception timestamp ---
    inception_time: int | None = Field(
        default=None, description="The inception time of an RRSIG record in Epoch seconds format."
    )  # --- read-only ---
    key_tag: int | None = Field(
        default=None,
        description="The key tag value of the DNSKEY RR that validates the signature.",
    )  # --- read-only: number of labels in the original RRSIG owner name ---
    labels: int | None = Field(
        default=None,
        description="The number of labels in the name of the RRset signed with the RRSIG object.",
    )  # --- read-only ---
    last_queried: int | None = Field(
        default=None, description="The time of the last DNS query in Epoch seconds format."
    )  # --- read-only: owner name ---
    name: str | None = Field(
        default=None, description="The name of the RRSIG record in FQDN format."
    )  # --- read-only: original TTL of the covered RRset ---
    original_ttl: int | None = Field(
        default=None, description="The TTL value of the RRset covered by the RRSIG record."
    )  # --- read-only: base64-encoded cryptographic signature ---
    signature: str | None = Field(
        default=None,
        description="The Base64 encoded cryptographic signature that covers the RRSIG RDATA of the RRSIG Record object.",
    )  # --- read-only: name of the signing key's zone ---
    signer_name: str | None = Field(
        default=None,
        description="The domain name of the zone in FQDN format that contains the signed RRset.",
    )  # --- read-only ---
    ttl: int | None = Field(
        default=None,
        description="The Time To Live (TTL) value for the record. A 32-bit unsigned integer that represents the duration, in seconds, for which the record is valid (cached). Zero indicates that the record should not be cached.",
    )  # --- read-only: RR type being covered ---
    type_covered: str | None = Field(
        default=None, description="The RR type covered by the RRSIG record."
    )  # --- read-only ---
    use_ttl: bool | None = Field(
        default=None, description="Use flag for: ttl"
    )  # --- read-only ---
    uuid: str | None = Field(
        default=None, description="Universally Unique ID assigned for this object"
    )  # --- read-only ---
    view: str | None = Field(
        default=None,
        description='The name of the DNS View in which the record resides. Example: "external".',
    )  # --- read-only ---
    zone: str | None = Field(
        default=None,
        description='The name of the zone in which the record resides. Example: "zone.com". If a view is not specified when searching by zone, the default view is used.',
    )
