# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
"""RecordDnskey - NIOS DNS DNSKEY record.

All 16 properties from ``components.schemas.RecordDnskey`` in the v2.14 DNS
swagger are represented here.  DNSSEC records are generated by the zone signer
and are almost entirely read-only; only ``_ref`` is writable.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Read-only fields (swagger readOnly: true) - all 15 non-_ref fields
# ---------------------------------------------------------------------------
READONLY_FIELDS: frozenset[str] = frozenset(
    {
        "algorithm",
        "comment",
        "creation_time",
        "creator",
        "dns_name",
        "flags",
        "key_tag",
        "last_queried",
        "name",
        "public_key",
        "ttl",
        "use_ttl",
        "uuid",
        "view",
        "zone",
    }
)


# ---------------------------------------------------------------------------
# Main RecordDnskey model
# ---------------------------------------------------------------------------


class RecordDnskey(BaseModel):
    """NIOS DNS DNSKEY record.

    All 16 swagger properties are present.  Almost every field is read-only
    (generated by the DNSSEC signer).  Read-only fields are collected in
    :data:`READONLY_FIELDS`; the resource strips them before PUT/POST.
    """

    model_config = ConfigDict(populate_by_name=True, extra="allow")

    ref: str | None = Field(default=None, alias="_ref", description="The reference to the object.")

    # --- read-only: signing algorithm ---
    algorithm: (
        Literal[
            "DSA",
            "ECDSAP256SHA256",
            "ECDSAP384SHA384",
            "NSEC3DSA",
            "NSEC3RSASHA1",
            "RSAMD5",
            "RSASHA1",
            "RSASHA256",
            "RSASHA512",
        ]
        | str
        | None
    ) = Field(
        default=None, description="The public key encryption algorithm of a DNSKEY Record object."
    )  # --- read-only: operator comment ---
    comment: str | None = Field(
        default=None, description="The comment for the record."
    )  # --- read-only ---
    creation_time: int | None = Field(
        default=None, description="The creation time of the record."
    )  # --- read-only ---
    creator: Literal["SYSTEM"] | str | None = Field(
        default=None, description="The record creator."
    )  # --- read-only ---
    dns_name: str | None = Field(
        default=None, description="Name of a DNSKEY record in punycode format."
    )  # --- read-only: DNSKEY flags bitmask ---
    flags: int | None = Field(
        default=None,
        description='The flags field is a 16-bit unsigned integer. Currently, only two bits of this value are used: the least significant bit and bit 7. The other bits are reserved for future use and must be zero. If bit 7 is set to 1, the key is a DNS zone key. Otherwise, the key is not a zone key and cannot be used to verify zone data. The least significant bit indicates "secure entry point property". If it is not zero, the key is a key signing key (KSK type). Otherwise, the key type is ZSK.',
    )  # --- read-only ---
    key_tag: int | None = Field(
        default=None,
        description="The key tag identifying the public key of a DNSKEY Record object.",
    )  # --- read-only ---
    last_queried: int | None = Field(
        default=None, description="The time of the last DNS query in Epoch seconds format."
    )  # --- read-only: owner name ---
    name: str | None = Field(
        default=None,
        description="The name of the DNSKEY record in FQDN format. It has to be the same as the zone, where the record resides.",
    )  # --- read-only: base64-encoded public key ---
    public_key: str | None = Field(
        default=None,
        description="The public key. The format of the returned value depends on the key algorithm.",
    )  # --- read-only ---
    ttl: int | None = Field(
        default=None,
        description="The Time To Live (TTL) value for the record. A 32-bit unsigned integer that represents the duration, in seconds, for which the record is valid (cached). Zero indicates that the record should not be cached.",
    )  # --- read-only ---
    use_ttl: bool | None = Field(
        default=None, description="Use flag for: ttl"
    )  # --- read-only ---
    uuid: str | None = Field(
        default=None, description="Universally Unique ID assigned for this object"
    )  # --- read-only ---
    view: str | None = Field(
        default=None,
        description='The name of the DNS View in which the record resides. Example: "external".',
    )  # --- read-only ---
    zone: str | None = Field(
        default=None,
        description='The name of the zone in which the record resides. Example: "zone.com". If a view is not specified when searching by zone, the default view is used.',
    )
