# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
"""RecordNsec3param - NIOS DNS NSEC3PARAM record.

All 16 properties from ``components.schemas.RecordNsec3param`` in the v2.14 DNS
swagger are represented here.  DNSSEC NSEC3PARAM records are generated by the
zone signer; 14 of 16 fields are read-only.  The ``cloud_info`` field is writable.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from ibx_nios_sdk.dns.models._shared import CloudInfo

# ---------------------------------------------------------------------------
# Read-only fields (swagger readOnly: true)
# ---------------------------------------------------------------------------
READONLY_FIELDS: frozenset[str] = frozenset(
    {
        "algorithm",
        "cloud_info",
        "creation_time",
        "creator",
        "dns_name",
        "flags",
        "iterations",
        "last_queried",
        "name",
        "salt",
        "ttl",
        "use_ttl",
        "uuid",
        "view",
        "zone",
    }
)


# ---------------------------------------------------------------------------
# Main RecordNsec3param model
# ---------------------------------------------------------------------------


class RecordNsec3param(BaseModel):
    """NIOS DNS NSEC3PARAM record.

    All 16 swagger properties are present.  Almost every field is read-only
    (generated by the DNSSEC signer).  ``cloud_info`` is the only non-ref
    writable field.  Read-only fields are collected in :data:`READONLY_FIELDS`;
    the resource strips them before PUT/POST.
    """

    model_config = ConfigDict(populate_by_name=True, extra="allow")

    ref: str | None = Field(default=None, alias="_ref", description="The reference to the object.")

    # --- read-only: hash algorithm (e.g. SHA-1) ---
    algorithm: (
        Literal[
            "DSA",
            "ECDSAP256SHA256",
            "ECDSAP384SHA384",
            "NSEC3DSA",
            "NSEC3RSASHA1",
            "RSAMD5",
            "RSASHA1",
            "RSASHA256",
            "RSASHA512",
        ]
        | str
        | None
    ) = Field(
        default=None, description="The hash algorithm that was used."
    )  # --- writable: cloud delegation metadata ---
    cloud_info: CloudInfo | None = Field(
        default=None, description="Cloud API related information for the object."
    )  # --- read-only ---
    creation_time: int | None = Field(
        default=None, description="The creation time of the record."
    )  # --- read-only ---
    creator: Literal["SYSTEM", "STATIC", "DYNAMIC"] | str | None = Field(
        default=None, description="Creator of the record."
    )  # --- read-only ---
    dns_name: str | None = Field(
        default=None, description="Name for an NSEC3PARAM record in punycode format."
    )  # --- read-only: NSEC3PARAM flags bitmask ---
    flags: int | None = Field(
        default=None,
        description="The set of 8 one-bit flags, of which only one flag, the Opt-Out flag, is defined by RFC 5155. The Opt-Out flag indicates whether the NSEC3 record covers unsigned delegations.",
    )  # --- read-only: hash iteration count ---
    iterations: int | None = Field(
        default=None, description="The number of times the hash function was performed."
    )  # --- read-only ---
    last_queried: int | None = Field(
        default=None, description="The time of the last DNS query in Epoch seconds format."
    )  # --- read-only: owner name ---
    name: str | None = Field(
        default=None,
        description="The name of the NSEC3PARAM record in FQDN format. It has to be the same as the zone, where the record resides.",
    )  # --- read-only: salt (hex string, "-" for empty) ---
    salt: str | None = Field(
        default=None,
        description="A series of case-insensitive hexadecimal digits. It is appended to the original owner name as protection against pre-calculated dictionary attacks. A new salt value is generated when the ZSK rolls over, for which the user can control the period. For a random salt value, the selected length is between one and 15 octets.",
    )  # --- read-only ---
    ttl: int | None = Field(
        default=None,
        description="The Time To Live (TTL) value for the record. A 32-bit unsigned integer that represents the duration, in seconds, for which the record is valid (cached). Zero indicates that the record should not be cached.",
    )  # --- read-only ---
    use_ttl: bool | None = Field(
        default=None, description="Use flag for: ttl"
    )  # --- read-only ---
    uuid: str | None = Field(
        default=None, description="Universally Unique ID assigned for this object"
    )  # --- read-only ---
    view: str | None = Field(
        default=None,
        description='The name of the DNS View in which the record resides. Example: "external".',
    )  # --- read-only ---
    zone: str | None = Field(
        default=None,
        description='The name of the zone in which the record resides. Example: "zone.com". If a view is not specified when searching by zone, the default view is used.',
    )
