# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
"""RecordNsec3 - NIOS DNS NSEC3 record.

All 18 properties from ``components.schemas.RecordNsec3`` in the v2.14 DNS
swagger are represented here.  DNSSEC NSEC3 records are generated by the zone
signer; 16 of 18 fields are read-only.  The ``cloud_info`` field is writable.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from ibx_nios_sdk.dns.models._shared import CloudInfo

# ---------------------------------------------------------------------------
# Read-only fields (swagger readOnly: true)
# ---------------------------------------------------------------------------
READONLY_FIELDS: frozenset[str] = frozenset(
    {
        "algorithm",
        "cloud_info",
        "creation_time",
        "creator",
        "dns_name",
        "flags",
        "iterations",
        "last_queried",
        "name",
        "next_owner_name",
        "rrset_types",
        "salt",
        "ttl",
        "use_ttl",
        "uuid",
        "view",
        "zone",
    }
)


# ---------------------------------------------------------------------------
# Main RecordNsec3 model
# ---------------------------------------------------------------------------


class RecordNsec3(BaseModel):
    """NIOS DNS NSEC3 record.

    All 18 swagger properties are present.  Almost every field is read-only
    (generated by the DNSSEC signer).  ``cloud_info`` is the only non-ref
    writable field.  Read-only fields are collected in :data:`READONLY_FIELDS`;
    the resource strips them before PUT/POST.
    """

    model_config = ConfigDict(populate_by_name=True, extra="allow")

    ref: str | None = Field(default=None, alias="_ref", description="The reference to the object.")

    # --- read-only: hash algorithm (e.g. SHA-1) ---
    algorithm: (
        Literal[
            "DSA",
            "ECDSAP256SHA256",
            "ECDSAP384SHA384",
            "NSEC3DSA",
            "NSEC3RSASHA1",
            "RSAMD5",
            "RSASHA1",
            "RSASHA256",
            "RSASHA512",
        ]
        | str
        | None
    ) = Field(
        default=None, description="The hash algorithm that was used."
    )  # --- writable: cloud delegation metadata ---
    cloud_info: CloudInfo | None = Field(
        default=None, description="Cloud API related information for the object."
    )  # --- read-only ---
    creation_time: int | None = Field(
        default=None, description="The creation time of the record."
    )  # --- read-only ---
    creator: Literal["SYSTEM", "STATIC", "DYNAMIC"] | str | None = Field(
        default=None, description="Creator of the record."
    )  # --- read-only ---
    dns_name: str | None = Field(
        default=None, description="Name for an NSEC3 record in punycode format."
    )  # --- read-only: NSEC3 flags bitmask ---
    flags: int | None = Field(
        default=None,
        description="The set of 8 one-bit flags, of which only one flag, the Opt-Out flag, is defined by RFC 5155. The Opt-Out flag indicates whether the NSEC3 record covers unsigned delegations.",
    )  # --- read-only: hash iteration count ---
    iterations: int | None = Field(
        default=None,
        description="The number of times the hash function was performed. RFC 9276 Section 3.1 mandates that this value MUST be set to zero (0) to ensure DNSSEC resolver compatibility and alleviate computational burdens on validating resolvers.",
    )  # --- read-only ---
    last_queried: int | None = Field(
        default=None, description="The time of the last DNS query in Epoch seconds format."
    )  # --- read-only: hashed owner name ---
    name: str | None = Field(
        default=None, description="The name of the NSEC3 record in FQDN format."
    )  # --- read-only: next hashed owner name ---
    next_owner_name: str | None = Field(
        default=None,
        description="The hashed next owner name that has authoritative data or that contains a delegation point NS record.",
    )  # --- read-only: list of RR type mnemonics covered ---
    rrset_types: list[str] | None = Field(
        default=None,
        description="The RRSet types that exist at the original owner name of the NSEC3 RR.",
    )  # --- read-only: salt (hex string, "-" for empty) ---
    salt: str | None = Field(
        default=None,
        description="A series of case-insensitive hexadecimal digits. It is appended to the original owner name as protection against pre-calculated dictionary attacks. A new salt value is generated when ZSK rolls over. You can control the period of the rollover. RFC 9276 recommends using an empty salt (0 octets) for optimal resolver compatibility and reduced computational overhead. For random salt values, the selected length is between zero and 255 octets.",
    )  # --- read-only ---
    ttl: int | None = Field(
        default=None,
        description="The Time To Live (TTL) value for the record. A 32-bit unsigned integer that represents the duration, in seconds, for which the record is valid (cached). Zero indicates that the record should not be cached.",
    )  # --- read-only ---
    use_ttl: bool | None = Field(
        default=None, description="Use flag for: ttl"
    )  # --- read-only ---
    uuid: str | None = Field(
        default=None, description="Universally Unique ID assigned for this object"
    )  # --- read-only ---
    view: str | None = Field(
        default=None,
        description='The name of the DNS View in which the record resides. Example: "external".',
    )  # --- read-only ---
    zone: str | None = Field(
        default=None,
        description='The name of the zone in which the record resides. Example: "zone.com". If a view is not specified when searching by zone, the default view is used.',
    )
