# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
"""Scheduledtask - NIOS scheduled task object.

Operations: GET collection, GET by ref, PUT, DELETE (no POST).

WAPI type: scheduledtask

NOTES:
- Many fields are read-only (status, audit trail, execution details).
- 'changed_objects' is a list of nested objects; typed as list[dict[str, Any]] | None.
- 'dependent_tasks' and 'execution_details' are list fields.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

READONLY_FIELDS: frozenset[str] = frozenset(
    {
        "approver",
        "changed_objects",
        "dependent_tasks",
        "execution_details",
        "execution_details_type",
        "execution_status",
        "execution_time",
        "is_network_insight_task",
        "member",
        "predecessor_task",
        "submit_time",
        "submitter",
        "task_id",
        "task_type",
        "ticket_number",
        "uuid",
    }
)


class Scheduledtask(BaseModel):
    """NIOS scheduled task."""

    model_config = ConfigDict(populate_by_name=True, extra="allow")

    ref: str | None = Field(default=None, alias="_ref", description="The reference to the object.")

    # --- read-only ---
    approver: str | None = Field(default=None, description="The approver of the task.")
    changed_objects: list[dict[str, Any]] | None = Field(
        default=None, description="A list of objects that are affected by the task."
    )
    dependent_tasks: list[dict[str, Any] | str] | None = Field(
        default=None,
        description="If this scheduled task has dependent tasks, their references will be returned in this field.",
    )
    execution_details: list[str] | None = Field(
        default=None,
        description="Messages generated by the execution of the scheduled task after its completion.",
    )
    execution_details_type: Literal["NONE", "WARNING"] | str | None = Field(
        default=None,
        description="The type of details generated by the execution of the scheduled task after its completion.",
    )
    execution_status: (
        Literal["COMPLETED", "FAILED", "PENDING", "WAITING_EXECUTION"] | str | None
    ) = Field(default=None, description="The execution status of the task.")
    execution_time: int | None = Field(
        default=None, description="The time when the appliance executed the task."
    )
    is_network_insight_task: bool | None = Field(
        default=None, description="Indicates whether this is a Network Insight scheduled task."
    )
    member: str | None = Field(default=None, description="The member where this task was created.")
    predecessor_task: str | None = Field(
        default=None,
        description="If this scheduled task has a predecessor task set, its reference will be returned in this field.",
    )
    submit_time: int | None = Field(
        default=None, description="The time when the task was submitted."
    )
    submitter: str | None = Field(default=None, description="The submitter of the task.")
    task_id: int | None = Field(default=None, description="The task ID.")
    task_type: Literal["OBJECT_CHANGE", "PORT_CONTROL"] | str | None = Field(
        default=None, description="The task type."
    )
    ticket_number: str | None = Field(default=None, description="The task ticket number.")
    uuid: str | None = Field(
        default=None, description="Universally Unique ID assigned for this object"
    )  # --- writable ---
    approval_status: Literal["APPROVED", "NONE", "PENDING", "REJECTED"] | str | None = Field(
        default=None, description="The approval status of the task."
    )
    approver_comment: str | None = Field(
        default=None, description="The comment specified by the approver of the task."
    )
    automatic_restart: bool | None = Field(
        default=None,
        description="Indicates whether there will be an automatic restart when the appliance executes the task.",
    )
    execute_now: bool | None = Field(
        default=None,
        description="If this field is set to True the specified task will be executed immediately.",
    )
    re_execute_task: bool | None = Field(
        default=None,
        description="If set to True, if the scheduled task is a Network Insight task and it failed, a new task will be cloned from this task and re-executed.",
    )
    scheduled_time: int | None = Field(
        default=None, description="The time when the task is scheduled to occur."
    )
    submitter_comment: str | None = Field(
        default=None, description="The comment specified by the submitter of the task."
    )
