# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
# src/ibx_nios_sdk/_restrictions.py
"""Per-object-type restrictions on read/create/update/delete.

Generated by ``tools/refresh_object_restrictions.py`` - do not edit by hand.

NIOS refuses operations an object type does not support, answering
``AdmConProtoError: Operation <op> not allowed for <type>``: a read-only
aggregate such as ``allrecords`` rejects every mutation, a singleton such as
``grid`` rejects ``delete``, and a function-only type such as ``dtc`` rejects
even ``read`` while still accepting ``call_function``.
:class:`~ibx_nios_sdk._resource.WapiResource` consults this table so those calls
raise :class:`~ibx_nios_sdk._exceptions.UnsupportedOperationError` locally
instead of making a request the grid will refuse.

Source: grid ?_schema restrictions via tests/fixtures/wapi_schema_v2.14.json
"""

from __future__ import annotations

from typing import Final

#: Operations a resource gates. ``call_function`` is never gated.
OPERATIONS: Final = frozenset({"read", "create", "update", "delete"})

#: WAPI object type -> operations that type does not support. Types absent from
#: this mapping support all of :data:`OPERATIONS`.
RESTRICTED_OPS: Final[dict[str, frozenset[str]]] = {
    "allendpoints": frozenset({"create", "delete", "update"}),
    "allnsgroup": frozenset({"create", "delete", "update"}),
    "allrecords": frozenset({"create", "delete", "update"}),
    "allrpzrecords": frozenset({"create", "delete", "update"}),
    "authpolicy": frozenset({"create", "delete"}),
    "cacertificate": frozenset({"create", "update"}),
    "capacityreport": frozenset({"create", "delete", "update"}),
    "captiveportal": frozenset({"create", "delete"}),
    "csvimporttask": frozenset({"create", "delete"}),
    "db_objects": frozenset({"create", "delete", "update"}),
    "dbsnapshot": frozenset({"create", "delete", "update"}),
    "deleted_objects": frozenset({"create", "delete", "read", "update"}),
    "dhcp:statistics": frozenset({"create", "delete", "update"}),
    "discovery": frozenset({"create", "delete", "read", "update"}),
    "discovery:device": frozenset({"create", "delete"}),
    "discovery:devicecomponent": frozenset({"create", "delete", "update"}),
    "discovery:deviceinterface": frozenset({"create", "delete"}),
    "discovery:deviceneighbor": frozenset({"create", "delete", "update"}),
    "discovery:devicesupportbundle": frozenset({"create", "update"}),
    "discovery:diagnostictask": frozenset({"create", "delete", "update"}),
    "discovery:gridproperties": frozenset({"create", "delete"}),
    "discovery:memberproperties": frozenset({"create", "delete"}),
    "discovery:sdnnetwork": frozenset({"create", "delete", "update"}),
    "discovery:status": frozenset({"create", "delete", "update"}),
    "discovery:vrf": frozenset({"create", "delete", "update"}),
    "discoverytask": frozenset({"create", "delete"}),
    "distributionschedule": frozenset({"create", "delete"}),
    "dtc": frozenset({"create", "delete", "read", "update"}),
    "dtc:allrecords": frozenset({"create", "delete", "update"}),
    "dtc:certificate": frozenset({"create", "delete", "update"}),
    "dtc:monitor": frozenset({"create", "delete", "update"}),
    "dtc:object": frozenset({"create", "delete", "update"}),
    "dtc:topology:label": frozenset({"create", "delete", "update"}),
    "dtc:topology:rule": frozenset({"create", "delete"}),
    "federatedrealms": frozenset({"create", "delete", "update"}),
    "fedipamop": frozenset({"create", "delete", "read", "update"}),
    "gmcschedule": frozenset({"create", "delete"}),
    "grid": frozenset({"create", "delete"}),
    "grid:cloudapi": frozenset({"create", "delete"}),
    "grid:cloudapi:cloudstatistics": frozenset({"create", "delete", "update"}),
    "grid:cloudapi:tenant": frozenset({"create", "delete"}),
    "grid:cloudapi:vm": frozenset({"create", "delete"}),
    "grid:cloudapi:vmaddress": frozenset({"create", "delete", "update"}),
    "grid:dashboard": frozenset({"create", "delete"}),
    "grid:dhcpproperties": frozenset({"create", "delete"}),
    "grid:dns": frozenset({"create", "delete"}),
    "grid:filedistribution": frozenset({"create", "delete"}),
    "grid:license_pool": frozenset({"create", "delete", "update"}),
    "grid:license_pool_container": frozenset({"create", "delete", "update"}),
    "grid:maxminddbinfo": frozenset({"create", "delete", "update"}),
    "grid:member:cloudapi": frozenset({"create", "delete"}),
    "grid:servicerestart:group:order": frozenset({"delete", "read", "update"}),
    "grid:servicerestart:request": frozenset({"create", "delete", "update"}),
    "grid:servicerestart:request:changedobject": frozenset({"create", "delete", "update"}),
    "grid:servicerestart:status": frozenset({"create", "delete", "update"}),
    "grid:threatinsight": frozenset({"create", "delete"}),
    "grid:threatprotection": frozenset({"create", "delete"}),
    "grid:x509certificate": frozenset({"create", "delete", "update"}),
    "hostnamerewritepolicy": frozenset({"create", "delete", "update"}),
    "hsm:allgroups": frozenset({"create", "delete", "update"}),
    "ipam:statistics": frozenset({"create", "delete", "update"}),
    "ipv4address": frozenset({"create", "update"}),
    "ipv6address": frozenset({"create", "update"}),
    "kerberoskey": frozenset({"create", "update"}),
    "lease": frozenset({"create", "update"}),
    "license:gridwide": frozenset({"create", "update"}),
    "localuser:authservice": frozenset({"create", "delete", "update"}),
    "mastergrid": frozenset({"create", "delete"}),
    "member:dhcpproperties": frozenset({"create", "delete"}),
    "member:dns": frozenset({"create", "delete"}),
    "member:filedistribution": frozenset({"create", "delete"}),
    "member:license": frozenset({"create", "update"}),
    "member:parentalcontrol": frozenset({"create", "delete"}),
    "member:threatinsight": frozenset({"create", "delete"}),
    "member:threatprotection": frozenset({"create", "delete"}),
    "membercloudsync": frozenset({"create", "delete"}),
    "memberdfp": frozenset({"create", "delete"}),
    "msserver:adsites:domain": frozenset({"create", "delete", "update"}),
    "multiregions": frozenset({"create", "delete", "update"}),
    "network_discovery": frozenset({"create", "delete", "read", "update"}),
    "notification:rest:template": frozenset({"create"}),
    "orderedranges": frozenset({"create", "delete"}),
    "orderedresponsepolicyzones": frozenset({"create", "delete"}),
    "outbound:cloudclient": frozenset({"create", "delete"}),
    "parentalcontrol:subscriber": frozenset({"create", "delete"}),
    "record:dhcid": frozenset({"create", "update"}),
    "record:dnskey": frozenset({"create", "delete", "update"}),
    "record:ds": frozenset({"create", "update"}),
    "record:dtclbdn": frozenset({"create", "delete", "update"}),
    "record:host_ipv4addr": frozenset({"create", "delete"}),
    "record:host_ipv6addr": frozenset({"create", "delete"}),
    "record:nsec": frozenset({"create", "delete", "update"}),
    "record:nsec3": frozenset({"create", "delete", "update"}),
    "record:nsec3param": frozenset({"create", "delete", "update"}),
    "record:rrsig": frozenset({"create", "delete", "update"}),
    "restartservicestatus": frozenset({"create", "delete", "update"}),
    "rir": frozenset({"create", "delete"}),
    "scavengingtask": frozenset({"create", "delete", "update"}),
    "scheduledtask": frozenset({"create"}),
    "smartfolder:children": frozenset({"create", "delete", "update"}),
    "superhostchild": frozenset({"create", "delete", "update"}),
    "taxii": frozenset({"create", "delete"}),
    "threatinsight:cloudclient": frozenset({"create", "delete"}),
    "threatinsight:insight_allowlist": frozenset({"create", "delete", "update"}),
    "threatinsight:moduleset": frozenset({"create", "delete", "update"}),
    "threatprotection:profile:rule": frozenset({"create", "delete"}),
    "threatprotection:rule": frozenset({"create", "delete"}),
    "threatprotection:rulecategory": frozenset({"create", "delete", "update"}),
    "threatprotection:ruleset": frozenset({"create"}),
    "threatprotection:ruletemplate": frozenset({"create", "delete", "update"}),
    "threatprotection:statistics": frozenset({"create", "delete", "update"}),
    "upgradeschedule": frozenset({"create", "delete"}),
    "upgradestatus": frozenset({"create", "delete", "update"}),
    "userprofile": frozenset({"create", "delete"}),
    "zone_auth_discrepancy": frozenset({"create", "delete", "update"}),
}


def restricted_ops(wapi_type: str) -> frozenset[str]:
    """Return the operations ``wapi_type`` does not support.

    Args:
        wapi_type: WAPI object type string, e.g. ``"allrecords"``.

    Returns:
        A frozenset of operation names drawn from :data:`OPERATIONS`; empty when
        the type supports every operation, or is unknown to the table.
    """
    return RESTRICTED_OPS.get(wapi_type, frozenset())
