#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
"""Regenerate ``src/ibx_nios_sdk/_restrictions.py``.

Each WAPI object type supports only some of read/create/update/delete. NIOS
reports the disallowed ones as the object schema's ``restrictions`` list; the
published OpenAPI specs approximate the same thing by omitting the operation.
This tool builds the SDK's restriction table from whichever source is available,
preferring the grid snapshot:

1. ``restrictions`` recorded per object in ``tests/fixtures/wapi_schema_v2.14.json``
   by ``tools/refresh_wapi_schema_snapshot.py`` (authoritative - read from a grid).
2. The methods declared per path in a checkout of github.com/infobloxopen/nios-swagger
   (``--swagger`` or ``$NIOS_SWAGGER_DIR``, pointing at ``swagger-ui/openspec/v2.14``).

When both are present the snapshot wins and any disagreement is reported on
stderr, since the specs are known to be wrong in places.

    python tools/refresh_object_restrictions.py \\
        --swagger ~/src/nios-swagger/swagger-ui/openspec/v2.14
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from tests.wapi_schema import SNAPSHOT, iter_resources  # noqa: E402

TARGET = ROOT / "src" / "ibx_nios_sdk" / "_restrictions.py"

# Operations the table can gate; mirrored as OPERATIONS in the output.
OPERATIONS = frozenset({"read", "create", "update", "delete"})

# OpenAPI method -> SDK operation name.
_METHOD_OPS = {"get": "read", "post": "create", "put": "update", "delete": "delete"}

_HEADER = '''# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Infoblox, Inc.
# src/ibx_nios_sdk/_restrictions.py
"""Per-object-type restrictions on read/create/update/delete.

Generated by ``tools/refresh_object_restrictions.py`` - do not edit by hand.

NIOS refuses operations an object type does not support, answering
``AdmConProtoError: Operation <op> not allowed for <type>``: a read-only
aggregate such as ``allrecords`` rejects every mutation, a singleton such as
``grid`` rejects ``delete``, and a function-only type such as ``dtc`` rejects
even ``read`` while still accepting ``call_function``.
:class:`~ibx_nios_sdk._resource.WapiResource` consults this table so those calls
raise :class:`~ibx_nios_sdk._exceptions.UnsupportedOperationError` locally
instead of making a request the grid will refuse.

Source: {source}
"""

from __future__ import annotations

from typing import Final

#: Operations a resource gates. ``call_function`` is never gated.
OPERATIONS: Final = frozenset({{"read", "create", "update", "delete"}})

#: WAPI object type -> operations that type does not support. Types absent from
#: this mapping support all of :data:`OPERATIONS`.
RESTRICTED_OPS: Final[dict[str, frozenset[str]]] = {{
'''

_FOOTER = """}


def restricted_ops(wapi_type: str) -> frozenset[str]:
    \"\"\"Return the operations ``wapi_type`` does not support.

    Args:
        wapi_type: WAPI object type string, e.g. ``"allrecords"``.

    Returns:
        A frozenset of operation names drawn from :data:`OPERATIONS`; empty when
        the type supports every operation, or is unknown to the table.
    \"\"\"
    return RESTRICTED_OPS.get(wapi_type, frozenset())
"""


def _from_swagger(directory: Path) -> dict[str, frozenset[str]]:
    """Map object type -> unsupported ops from the methods each spec declares."""
    specs = sorted(directory.glob("*.json"))
    if not specs:
        raise SystemExit(f"no OpenAPI specs found in {directory}")
    methods: dict[str, set[str]] = {}
    for spec in specs:
        paths = json.loads(spec.read_text()).get("paths", {})
        for path, operations in paths.items():
            head = path.strip("/").split("/")[0]
            if not head or head.startswith("{"):
                continue
            methods.setdefault(head, set()).update(
                _METHOD_OPS[method] for method in operations if method in _METHOD_OPS
            )
    return {
        wapi_type: frozenset(OPERATIONS - supported)
        for wapi_type, supported in methods.items()
        if OPERATIONS - supported
    }


def _from_snapshot() -> dict[str, frozenset[str]]:
    """Map object type -> unsupported ops from the grid schema snapshot."""
    objects: dict[str, Any] = json.loads(SNAPSHOT.read_text())["objects"]
    restrictions = {
        wapi_type: frozenset(OPERATIONS & set(entry["restrictions"]))
        for wapi_type, entry in objects.items()
        if entry.get("restrictions")
    }
    return {wapi_type: ops for wapi_type, ops in restrictions.items() if ops}


def _render(table: dict[str, frozenset[str]], source: str) -> str:
    lines = [_HEADER.format(source=source)]
    for wapi_type in sorted(table):
        ops = ", ".join(f'"{op}"' for op in sorted(table[wapi_type]))
        lines.append(f'    "{wapi_type}": frozenset({{{ops}}}),\n')
    lines.append(_FOOTER)
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--swagger",
        type=Path,
        default=os.environ.get("NIOS_SWAGGER_DIR"),
        help="nios-swagger swagger-ui/openspec/v2.14 directory",
    )
    parser.add_argument("--out", type=Path, default=TARGET)
    args = parser.parse_args()

    known = {res.wapi_type for res in iter_resources()}
    snapshot = _from_snapshot()
    swagger = _from_swagger(args.swagger) if args.swagger else {}
    if not snapshot and not swagger:
        raise SystemExit(
            "no restriction data: refresh the schema snapshot from a grid, or pass "
            "--swagger / set NIOS_SWAGGER_DIR"
        )

    if snapshot:
        source = "grid ?_schema restrictions via tests/fixtures/wapi_schema_v2.14.json"
        table = snapshot
        for wapi_type in sorted(set(snapshot) | set(swagger)):
            grid, spec = snapshot.get(wapi_type, frozenset()), swagger.get(wapi_type, frozenset())
            if swagger and grid != spec:
                print(
                    f"disagreement {wapi_type}: grid={sorted(grid)} swagger={sorted(spec)} "
                    "(using grid)",
                    file=sys.stderr,
                )
    else:
        source = f"nios-swagger OpenAPI methods ({args.swagger})"
        table = swagger

    unknown = sorted(set(table) - known)
    for wapi_type in unknown:
        print(f"skipped {wapi_type}: not an SDK resource type", file=sys.stderr)
    table = {wapi_type: ops for wapi_type, ops in table.items() if wapi_type in known}

    args.out.write_text(_render(table, source))
    print(f"wrote {len(table)} restricted object types to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
